Ingredient.create(name: "lemon")
Ingredient.create(name: "ice")
Ingredient.create(name: "mint leaves")
Ingredient.create(name: "White rum")
Ingredient.create(name: "Simple syrup")
Ingredient.create(name: "Lime juice")
